QLPC/QLPC/Models/DataModel/KHACHHANG.cs
namespace QLPC.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("KHACHHANG")]
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            BAOHANHs = new HashSet<BAOHANH>();
            COMMENTs = new HashSet<COMMENT>();
            GIOHANGs = new HashSet<GIOHANG>();
            MUABANs = new HashSet<MUABAN>();
            RATINGs = new HashSet<RATING>();
            VIEWs = new HashSet<VIEW>();
            SANPHAMs = new HashSet<SANPHAM>();
        }

        [Key]
        [Display(Name = "ID")]
        public int MAKH { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập đầy đủ tên khách hàng")]
        [StringLength(200, ErrorMessage = "Độ dài tối đa là 200 kí tự")]
        [Display(Name = "Tên khách hàng")]
        public string TENKH { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập đúng số điện thoại")]
        [Display(Name = "Điện thoại")]
        [StringLength(12, ErrorMessage = "Số điện thoại không đúng", MinimumLength = 10)]
        public string DCHIKH { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập địa chỉ khách hàng")]
        [StringLength(1000)]
        [Display(Name = "Địa chỉ khách hàng")]
        public string DTHOAIKH { get; set; }

        [StringLength(50)]
        [Display(Name = "Tỉnh")]
        public string TINH { get; set; }

        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        [StringLength(15, ErrorMessage = "Độ dài mật khẩu từ 6-15 kí tự", MinimumLength = 6)]
        public string PASS { get; set; }

        [StringLength(100, ErrorMessage = "Độ dài email dưới 100 kí tự.")]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Hãy nhập đúng Email của bạn")]
        public string EMAIL { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOHANH> BAOHANHs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUABAN> MUABANs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATING> RATINGs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIEW> VIEWs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}

QLPC/QLPC/Areas/Admin/Controllers/KhachhangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLPC.Models.BussinessModel;
using QLPC.Models.DataModel;
using PagedList;


namespace QLPC.Areas.Admin.Controllers
{
    public class KhachhangController : Controller
    {
        private QLPCDbContext db = new QLPCDbContext();

        // GET: Admin/Khachhang
        public ActionResult Index(int ? page)
        {
            var khachhangs = db.khachhang.ToList();
            var pageNumber = page ?? 1;
            var onePageOfKhachhang = khachhangs.ToPagedList(pageNumber, 20);
            ViewBag.khachhang = onePageOfKhachhang;
            return View(/*db.khachhang.ToList()*/);
        }

        // GET: Admin/Khachhang/Details/5
        public ActionResult Details(string id)
        {          
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHACHHANG kHACHHANG = db.khachhang.Find(id);
            ViewBag.luotmua = db.muaban.Where(x => x.MAKH.Equals(id)).Count();
            var sp = db.muaban.Include(s => s.SANPHAM).Where(x => x.MAKH.Equals(id)).ToList();
            //var sanphams = (from m in db.muaban //lấy danh sách sản phẩm mà người dùng mua
            //                                join s in db.sanpham
            //                                on m.SERIAL equals s.SERIAL
            //                                where m.MAKH.Equals(id)
            //                                select new 
            //                                {                   
            //                                    TENMAY = s.TENMAY,
            //                                    MODEL = s.MODEL,
            //                                    IMAGE = s.IMAGE,
            //                                    GIA = s.GIA
            //                                }).ToList();
            ViewBag.sanpham = sp;
            if (kHACHHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHACHHANG);
        }

        // GET: Admin/Khachhang/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Khachhang/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MAKH,TENKH,DCHIKH,DTHOAIKH,TINH,PASS,EMAIL")] KHACHHANG kHACHHANG)
        {
            if (ModelState.IsValid)
            {
                db.khachhang.Add(kHACHHANG);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: Admin/Khachhang/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHACHHANG kHACHHANG = db.khachhang.Find(id);
            if (kHACHHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHACHHANG);
        }

        // POST: Admin/Khachhang/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MAKH,TENKH,DCHIKH,DTHOAIKH,TINH,PASS,EMAIL")] KHACHHANG kHACHHANG)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kHACHHANG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kHACHHANG);
        }


        // POST: Admin/Khachhang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            KHACHHANG kHACHHANG = db.khachhang.Find(id);
            db.khachhang.Remove(kHACHHANG);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

QLPC/QLPC/Areas/Admin/Views/Khachhang/Create.cshtml
@model QLPC.Models.DataModel.KHACHHANG

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    <div class="box box-primary">
        <div class="box-header with-border"><h2>Thêm mới khách hàng</h2></div>
        <br />
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MAKH, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.MAKH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MAKH, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TENKH, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TENKH, new { htmlAttributes = new { @class = "form-control", placeholder = "Dưới 50 kí tự." } })
                    @Html.ValidationMessageFor(model => model.TENKH, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control", placeholder = "example@gmail.com" } })
                    @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DCHIKH, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.DCHIKH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DCHIKH, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TINH, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TINH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TINH, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DTHOAIKH, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.DTHOAIKH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DTHOAIKH, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PASS, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.PASS, new { htmlAttributes = new { @class = "form-control",  placeholder = "Từ 6 đến 15 kí tự." } })
                    @Html.ValidationMessageFor(model => model.PASS, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
        <div class="form-group box-footer">
            <div class="col-md-offset-3 col-md-9">
                <span>
                    <input type="submit" value="Thêm" class="btn btn-primary btn" /> &nbsp &nbsp
                    <a href="/Admin/Khachhang/Index"><input class="btn btn-default" type="button" value="Hủy" /></a>
                </span>
            </div>
        </div>
    </div>
 }

QLPC/QLPC/Areas/Admin/Views/Khachhang/Details.cshtml
@model QLPC.Models.DataModel.KHACHHANG
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="box box-primary">
    <div class="box-header ">
        <h3>Thông tin chi tiết khách hàng</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Thu gọn">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Đóng">
                <i class="fa fa-times"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <table class="table ">
            <tr>
                <td class="col-md-1"><b>ID:</b></td>
                <td class="col-md-2">@Model.MAKH</td>
                <td class="col-md-1"><b>Điện thoại:</b></td>
                <td class="col-md-2">@Model.DTHOAIKH </td>
                <td class="col-md-1"><b>Email: </b></td>
                <td class="col-md-3">@Model.EMAIL </td>
                <td class="col-md-1"><b>Tỉnh: </b></td>
                <td class="col-md-1">@Model.TINH </td>
            </tr>
            <tr>
                <td class="col-md-1"><b>Họ tên:</b></td>
                <td class="col-md-2"><p style="color:blue">@Model.TENKH</p></td>
                <td class="col-md-1"><b>Mật khẩu:</b></td>
                <td class="col-md-2">@Model.PASS </td>
                <td class="col-md-1"><b>Địa chỉ: </b></td>
                <td class="col-md-3">@Model.DCHIKH </td>
                <td class="col-md-1"><b>Lượt mua: </b></td>
                <td class="col-md-1">@ViewBag.luotmua</td>
            </tr>
        </table>
    </div>
    <div class="box-footer">
        <button type="button" onclick="location.href=' @Url.Action("Edit", "Khachhang", new { id = Model.MAKH })'" class="btn btn-primary">Cập nhật</button>
        <button type="button" onclick="location.href=' @Url.Action("Index", "Khachhang", new { id = Model.MAKH })'" class="btn btn-default">Trở về</button>
    </div>
</div>


<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Sản phẩm đã mua</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Thu gọn">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Đóng">
                <i class="fa fa-times"></i>
            </button>
        </div>
    </div>
    <div class="box-body" >
   @foreach(var item in ViewBag.sanpham){ 
         <div style="width:200px" class="active">
             <div><img src="@item.SANPHAM.IMAGE" width="200" height="200"/></div>
             <div style="text-align:center"><a href="/Admin/Sanpham/Details/@item.SERIAL">@item.SANPHAM.TENMAY @item.SANPHAM.MODEL</a></div>
         </div>
        }
    </div>
    <div class="box-footer">
        
    </div>
</div>

QLPC/QLPC/Areas/Admin/Views/Khachhang/Edit.cshtml
@model QLPC.Models.DataModel.KHACHHANG

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    <div class="box box-primary">
        <div class="box-header with-border"><h2>Cập nhật thông tin khách hàng</h2></div>
        <br />
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MAKH, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.MAKH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MAKH, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TENKH, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TENKH, new { htmlAttributes = new { @class = "form-control", placeholder = "Dưới 50 kí tự." } })
                    @Html.ValidationMessageFor(model => model.TENKH, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control", placeholder = "example@gmail.com" } })
                    @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DCHIKH, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.DCHIKH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DCHIKH, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TINH, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TINH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TINH, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DTHOAIKH, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.DTHOAIKH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DTHOAIKH, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PASS, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.PASS, new { htmlAttributes = new { @class = "form-control", placeholder = "Từ 6 đến 15 kí tự." } })
                    @Html.ValidationMessageFor(model => model.PASS, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
        <div class="form-group box-footer">
            <div class="col-md-offset-3 col-md-9">
                <span>
                    <input type="submit" value="Cập nhật" class="btn btn-primary btn" /> &nbsp &nbsp
                    <a href="/Admin/Khachhang/Index"><input class="btn btn-default" type="button" value="Hủy" /></a>
                </span>
            </div>
        </div>
    </div>
}

QLPC/QLPC/Areas/Admin/Views/Khachhang/Index.cshtml
@model IEnumerable<QLPC.Models.DataModel.KHACHHANG>

@{
    ViewBag.Title = "Danh sách khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@using PagedList.Mvc;
@using PagedList;

<div class="box box-primary">
    <div class="box-header with-border">
        <h2>Danh sách khách hàng</h2>
    </div>

    <a href="/Admin/Khachhang/Create"><input class="btn btn-primary" type="button" value="Thêm mới khách hàng" /></a>
    <table class="table table-responsive table-hover table-bordered table-condensed  ">
        <tr class="info">
            <th class="col-md-1" >
                @Html.DisplayNameFor(model => model.MAKH)
            </th>
            <th class="col-md-2">
                @Html.DisplayNameFor(model => model.TENKH)
            </th>
            <th class="col-md-5">
                @Html.DisplayNameFor(model => model.DCHIKH)
            </th>
            <th class="col-md-1">
                @Html.DisplayNameFor(model => model.DTHOAIKH)
            </th>
            <th class="col-md-1">
                @Html.DisplayNameFor(model => model.TINH)
            </th>
            <th class="col-md-2">Tùy chọn</th>
        </tr>

        @foreach (var item in ViewBag.khachhang)
        {
            <tr class="active ">
                <td class="col-md-1">
                    @item.MAKH
                </td>
                <td class="col-md-2">
                    @item.TENKH
                </td>
                <td class="col-md-5">
                    @item.DCHIKH
                </td>
                <td class="col-md-1">
                    @item.DTHOAIKH
                </td>
                <td class="col-md-1">
                    @item.TINH
                </td>
                <td class="btn-group col-md-2">
                    @Html.ActionLink(" ", "Edit", new { id = item.MAKH }, new { @class = "btn btn-primary glyphicon glyphicon-edit", data_toggle = "tooltip", title = "Cập nhật" })
                    @Html.ActionLink(" ", "Details", new { id = item.MAKH }, new { @class = "btn btn-primary glyphicon glyphicon-list-alt", data_toggle = "tooltip", title = "Xem" })
                    @Html.ActionLink(" ", "Delete", new { id = item.MAKH }, new { @class = "btn btn-primary glyphicon glyphicon-remove-sign disabled", data_toggle = "tooltip", title = "Xóa", @onclick = "return confirm('Khách hàng này sẽ được xóa khỏi danh dách! Bạn có muốn xóa?');" })
                </td>
            </tr>
        }
    </table>
    <div>
        @Html.PagedListPager((IPagedList)ViewBag.khachhang, page => Url.Action("Index", new { page }))
    </div>
</div>