QLPC/QLPC/Models/DataModel/NHANVIEN.cs
namespace QLPC.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("NHANVIEN")]
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            BAOHANHs = new HashSet<BAOHANH>();
        }

        [Key]
        [Display(Name = "ID")]
        public int MANV { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập đầy đủ họ tên!.")]
        [StringLength(50, ErrorMessage = "Tên có độ dài dưới 50 kí tự.")]
        [Display(Name = "Tên nhân viên")]
        public string TENNV { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số điện thoại!.")]
        [StringLength(12, ErrorMessage = "Hãy nhập đúng số điện thoại", MinimumLength = 10)]
        [Display(Name = "Điện thoại")]
        public string DTHOAINV { get; set; }

        [Required(ErrorMessage = "Vùi lòng nhập địa chỉ!.")]
        [StringLength(1000)]
        [Display(Name = "Địa chỉ")]
        public string DCHINV { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        [StringLength(15)]
        [Display(Name = "Mật khẩu")]
        public string PASS { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn quyền cho người dùng!.")]
        [Display(Name = "Quyền")]
        public int? GRANT { get; set; }

        [StringLength(100)]
        [Display(Name = "Email nhân viên")]
        [DataType(DataType.EmailAddress)]
        public string EMAIL { get; set; }

        [StringLength(1000)]
        [Display(Name = "Ảnh đại diện")]
        public string AVATAR { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOHANH> BAOHANHs { get; set; }
    }
}

QLPC/QLPC/Areas/Admin/Controllers/NhanvienController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLPC.Models.BussinessModel;
using QLPC.Models.DataModel;
using PagedList;

namespace QLPC.Areas.Admin.Controllers
{
    public class NhanvienController : Controller
    {
        private QLPCDbContext db = new QLPCDbContext();

        // GET: Admin/Nhanvien
        //Trang hiển thị danh sách nhân viên
        public ActionResult Index(int? page)
        {
            var products = db.nhanvien.ToList();
            var pageNumber = page ?? 1;
            var onePageOfNhanviens = products.ToPagedList(pageNumber, 5);
            ViewBag.OnePageOfNhanvien = onePageOfNhanviens;
            return View(/*db.nhanvien.ToList()*/);
        }

        // GET: Admin/Nhanvien/Details/5
        //Chuyển đến trang xem chi tiết thông tin nhân viên
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nHANVIEN = db.nhanvien.Find(id);
            if (nHANVIEN == null)
            {
                return HttpNotFound();
            }
            return View(nHANVIEN);
        }

        // GET: Admin/Nhanvien/Create
        //Di chuyển đến trang tạo nhân viên
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Nhanvien/Create
        //Tạo một nhân viên mới tuef những thông tin do người dùng nhập
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MANV,TENNV,DTHOAINV,DCHINV,PASS,GRANT,EMAIL,AVATAR")] NHANVIEN nHANVIEN)
        { 
            if (ModelState.IsValid)
            {
                nHANVIEN.AVATAR = "/Areas/Admin/Content/dist/img/" + nHANVIEN.AVATAR;
                db.nhanvien.Add(nHANVIEN);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: Admin/Nhanvien/Edit/5
        //Nhận vào một mã nhân viên sau đó chuyển đến trang xem chi tiết
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nHANVIEN = db.nhanvien.Find(id);
            if (nHANVIEN == null)
            {
                return HttpNotFound();
            }
            return View(nHANVIEN);
        }

        // POST: Admin/Nhanvien/Edit/5
        // Cập nhật thông tin nhân viên sau khi chỉnh sửa
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MANV,TENNV,DTHOAINV,DCHINV,PASS,GRANT,EMAIL,AVATAR")] NHANVIEN nHANVIEN)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nHANVIEN).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nHANVIEN);
        }

        // GET: Admin/Nhanvien/Delete/5
        //Xóa nhân viên từ danh sách
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nHANVIEN = db.nhanvien.Find(id);
            if (nHANVIEN != null)
            {
                db.nhanvien.Remove(nHANVIEN);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

    }
}

QLPC/QLPC/Areas/Admin/Views/Nhanvien/Create.cshtml
@model QLPC.Models.DataModel.NHANVIEN

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


    @using (Html.BeginForm())
    {
        <div class="box box-primary">
            <div class="box-header with-border"><h2>Thêm mới nhân viên</h2></div>
            <br />
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.TENNV, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.TENNV, new { htmlAttributes = new { @class = "form-control", placeholder = "Dưới 50 kí tự" } })
                        @Html.ValidationMessageFor(model => model.TENNV, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3"></div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DTHOAINV, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.DTHOAINV, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DTHOAINV, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3"></div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DCHINV, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.DCHINV, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DCHINV, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3"></div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PASS, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6 l">
                        @Html.EditorFor(model => model.PASS, new { htmlAttributes = new { @class = "form-control", placeholder = "Dưới 15 kí tự" } })
                        @Html.ValidationMessageFor(model => model.PASS, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3"></div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.GRANT, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-3 ">
                                @{
                                    List<SelectListItem> listItems = new List<SelectListItem>();
                                    listItems.Clear();
                                    listItems.Add(new SelectListItem { Text = "0" });
                                    listItems.Add(new SelectListItem { Text = "1" });
                                    listItems.Add(new SelectListItem { Text = "2" });
                                }
                                @*@Html.EditorFor(model => model.GRANT,new { htmlAttributes = new { @class = "form-control ", placeholder = "0: chưa cấp quyền; 1: nhân viên; 2: quản lí" } })*@
                                @Html.DropDownListFor(model => model.GRANT,listItems, new { @class = "form-control ", placeholder = "0: chưa cấp quyền; 1: nhân viên; 2: quản lí" } )
                                @Html.ValidationMessageFor(model => model.GRANT, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3 " style="color:crimson">0: chưa cấp quyền; 1: nhân viên; 2: quản lí</div>
                    <div class="col-md-3"></div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control", placeholder = "example@gmail.com" } })
                        @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger"})
                    </div>
                    <div class="col-md-3"></div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AVATAR, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.AVATAR, new { htmlAttributes = new { @class = "form-control", type="file"} })
                        @Html.ValidationMessageFor(model => model.AVATAR, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3"></div>
                </div>
            </div>
            <div class="form-group box-footer">
                <div class="col-md-offset-3 col-md-9">
                    <span>
                        <input type="submit" value="Thêm" class="btn btn-primary btn" /> &nbsp &nbsp
                        <a href="/Admin/Nhanvien/Index"><input class="btn btn-default" type="button" value="Hủy" /></a>
                    </span>
                </div>
            </div>
        </div>
    }

QLPC/QLPC/Areas/Admin/Views/Nhanvien/Details.cshtml
@model QLPC.Models.DataModel.NHANVIEN

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3>Thông tin chi tiết nhân viên</h3>
    </div>
    <div class="col-md-offset-3 col-md-9">
        <h3 style="margin-left:10px">Ông/Bà: @Model.TENNV</h3>
        <img src="@Model.AVATAR" class="img-responsive img-thumbnail" width="100" height="100" style="margin-left:90px" /> 
        <dl class="dl-horizontal">
            <dt>
                Mã nhân viên
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MANV)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TENNV)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TENNV)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DTHOAINV)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DTHOAINV)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DCHINV)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DCHINV)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PASS)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PASS)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GRANT)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GRANT)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EMAIL)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EMAIL)
            </dd>
        </dl>
    </div>
    <div class="box-footer">
        <button type="button" onclick="location.href=' @Url.Action("Edit", "Nhanvien", new { id = Model.MANV })'" class="btn btn-primary">Cập nhật</button>
        <button type="button" onclick="location.href=' @Url.Action("Index", "Nhanvien", new { id = Model.MANV })'" class="btn btn-default">Trở về</button>
    </div>
</div>

QLPC/QLPC/Areas/Admin/Views/Nhanvien/Edit.cshtml
@model QLPC.Models.DataModel.NHANVIEN

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MANV)
    <div class="box box-primary">
        <div class="box-header with-border"><h2>Cập nhật thông tin nhân viên</h2></div>
        <br />
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.TENNV, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TENNV, new { htmlAttributes = new { @class = "form-control", placeholder = "Dưới 50 kí tự" } })
                    @Html.ValidationMessageFor(model => model.TENNV, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DTHOAINV, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.DTHOAINV, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DTHOAINV, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DCHINV, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.DCHINV, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DCHINV, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PASS, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6 l">
                    @Html.EditorFor(model => model.PASS, new { htmlAttributes = new { @class = "form-control", placeholder = "Dưới 15 kí tự" } })
                    @Html.ValidationMessageFor(model => model.PASS, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GRANT, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-3 ">
                    @{
                        List<SelectListItem> listItems = new List<SelectListItem>();
                        listItems.Clear();
                        listItems.Add(new SelectListItem { Text = "0" });
                        listItems.Add(new SelectListItem { Text = "1" });
                        listItems.Add(new SelectListItem { Text = "2" });
                    }
                    @*@Html.EditorFor(model => model.GRANT,new { htmlAttributes = new { @class = "form-control ", placeholder = "0: chưa cấp quyền; 1: nhân viên; 2: quản lí" } })*@
                    @Html.DropDownListFor(model => model.GRANT, listItems, new { @class = "form-control ", placeholder = "0: chưa cấp quyền; 1: nhân viên; 2: quản lí" })
                    @Html.ValidationMessageFor(model => model.GRANT, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3 " style="color:crimson">0: chưa cấp quyền; 1: nhân viên; 2: quản lí</div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control", placeholder = "example@gmail.com" } })
                    @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AVATAR, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.AVATAR, new { htmlAttributes = new { @class = "form-control", type = "file" } })
                    @Html.ValidationMessageFor(model => model.AVATAR, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
        <div class="form-group box-footer">
            <div class="col-md-offset-3 col-md-9">
                <span>
                    <input type="submit" value="Cập nhật" class="btn btn-primary btn" /> &nbsp &nbsp
                    <a href="/Admin/Nhanvien/Index"><input class="btn btn-default" type="button" value="Hủy" /></a>
                </span>
            </div>
        </div>
    </div>
 }

QLPC/QLPC/Areas/Admin/Views/Nhanvien/Index.cshtml
@model IEnumerable<QLPC.Models.DataModel.NHANVIEN>

@{
    ViewBag.Title = "Danh sách nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@using PagedList.Mvc;
@using PagedList;


<div class="box box-primary">
    <div class="box-header with-border">
        <h2 >Danh sách nhân viên</h2>
    </div>

 <a href="/Admin/Nhanvien/Create"><input class="btn btn-primary" type="button" value="Thêm mới nhân viên"/></a>
 <table class="table table-responsive table-hover table-bordered table-condensed ">
    <tr class="info">
        <th class="">
            @Html.DisplayNameFor(model => model.MANV)
        </th>
        <th class="col-md-2">
            @Html.DisplayNameFor(model => model.TENNV)
        </th>
        <th class="col-md-1">
            @Html.DisplayNameFor(model => model.DTHOAINV)
        </th>
        <th class="col-md-4">
            @Html.DisplayNameFor(model => model.DCHINV)
        </th>
        <th class="col-md-1">
            @Html.DisplayNameFor(model => model.GRANT)
        </th>
        <th class="col-md-2">
            @Html.DisplayNameFor(model => model.EMAIL)
        </th>
        <th class="col-md-2">Tùy chọn</th>
    </tr>

@foreach (var item in ViewBag.OnePageOfNhanvien) {
    <tr class="active  ">
        <td>
            @(item.MANV)
        </td>
        <td >
            @item.TENNV
        </td>
        <td>
            @item.DTHOAINV
        </td>
        <td>
            @item.DCHINV
        </td>
        <td>
            @item.GRANT
        </td>
        <td>
            @item.EMAIL
        </td>
        <td>
            <div class="btn-group ">
                @*<button type="button" data-toggle="tooltip" title="Cập nhật" onclick="location.href=' @Url.Action("Edit", "Nhanvien", new { id = item.MANV })'" class ="btn btn-primary"><p class="glyphicon glyphicon-edit"></p></button>
                <button type="button" data-toggle="tooltip" title="Xem" onclick="location.href=' @Url.Action("Details", "Nhanvien", new { id = item.MANV })'" class="btn btn-primary"><p class="glyphicon glyphicon-list-alt"></p></button>
                <button type="button" data-toggle="tooltip" title="Xóa" onclick="location.href=' @Url.Action("Delete", "Nhanvien", new { id = item.MANV })'" class="btn btn-primary"><p class="glyphicon glyphicon-remove-sign"></p></button>*@
                @Html.ActionLink(" ", "Edit", new { id = item.MANV }, new { @class = "btn btn-primary glyphicon glyphicon-edit", data_toggle = "tooltip", title = "Cập nhật" }) 
                @Html.ActionLink(" ", "Details", new { id = item.MANV }, new { @class = "btn btn-primary glyphicon glyphicon-list-alt", data_toggle = "tooltip", title = "Xem" }) 
                @Html.ActionLink(" ", "Delete", new { id = item.MANV }, new {@class= "btn btn-primary glyphicon glyphicon-remove-sign disabled", data_toggle = "tooltip", title = "Xóa", @onclick = "return confirm('Nhân viên này sẽ được xóa khỏi danh dách! Bạn có muốn xóa?');" }) 
            </div>
        </td>
    </tr>
}
</table>

    <div class="box-footer">
        @Html.PagedListPager((IPagedList)ViewBag.OnePageOfNhanvien, page => Url.Action("Index", new { page }))
    </div>
</div>

<script>
$(document).ready(function(){
    $('[data_toggle="tooltip"]').tooltip();
});
</script>