QLPC/QLPC/Models/DataModel/SANPHAM.cs
namespace QLPC.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web.Mvc;

    [Table("SANPHAM")]
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            BAOHANHs = new HashSet<BAOHANH>();
            COMMENTs = new HashSet<COMMENT>();
            GIOHANGs = new HashSet<GIOHANG>();
            LINHKIENs = new HashSet<LINHKIEN>();
            MUABANs = new HashSet<MUABAN>();
            RATINGs = new HashSet<RATING>();
            RATINGs1 = new HashSet<RATING>();
            VIEWs = new HashSet<VIEW>();
            VIEWs1 = new HashSet<VIEW>();
            KHACHHANGs = new HashSet<KHACHHANG>();
        }

        [Key]
        [StringLength(50)]
        [Display(Name = "Mã sản phẩm")]
        public string SERIAL { get; set; }

        [Display(Name = "Mã hãng sản xuất")]
        public int MAHSX { get; set; }

        [Display(Name = "Mã nhà phân phối")]
        public int MANPP { get; set; }

        [StringLength(50)]
        [Display(Name = "Tên máy")]
        public string TENMAY { get; set; }

        [StringLength(100)]
        [Display(Name = "Mã hiệu (model)")]
        public string MODEL { get; set; }

        [Display(Name = "Giá niêm yết")]
        public decimal? GIA { get; set; }

        [Display(Name = "Số lượng")]
        public int? SOLUONG { get; set; }

        [Display(Name = "Thời gian bảo hành")]
        public int? THOIHANBAOHANH { get; set; }

        [StringLength(100)]
        [Display(Name = "Hình sản phẩm")]
        public string IMAGE { get; set; }

        [Column(TypeName = "xml")]
        [Display(Name = "Ảnh khác")]
        public string MOREIMAGE { get; set; }

        [Display(Name = "Giá khuyến mãi")]
        public decimal? GIAKHUYENMAI { get; set; }

        [Display(Name = "Mô tả chi tiết")]
        [DataType(DataType.MultilineText)]
        [AllowHtml]
        public string DETAIL { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "Ngày nhập hàng")]
        public DateTime? NGAYNHAP { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOHANH> BAOHANHs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }

        public virtual HANGSX HANGSX { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINHKIEN> LINHKIENs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUABAN> MUABANs { get; set; }

        public virtual NHAPHANPHOI NHAPHANPHOI { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATING> RATINGs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATING> RATINGs1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIEW> VIEWs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIEW> VIEWs1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
    }
}

QLPC/QLPC/Areas/Admin/Controllers/SanphamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLPC.Models.BussinessModel;
using QLPC.Models.DataModel;
using PagedList;

namespace QLPC.Areas.Admin.Controllers
{
    public class SanphamController : Controller
    {
        private QLPCDbContext db = new QLPCDbContext();

        // GET: Admin/Sanpham
        public ActionResult Index(int? page)
        {
            var sanpham = db.sanpham.Include(s => s.HANGSX).Include(s => s.NHAPHANPHOI).ToList();
            var pageNumber = page ?? 1;
            var onePageOfSanpham = sanpham.ToPagedList(pageNumber, 20);
            ViewBag.sanpham = onePageOfSanpham;
            return View();
        }

        // GET: Admin/Sanpham/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sANPHAM = db.sanpham.Include(s => s.HANGSX).Include(s => s.NHAPHANPHOI).Where(x => x.SERIAL.Equals(id));
            var lINHKIEN = db.linhkien.Include(s => s.SANPHAM).Where(x => x.SERIAL == id).OrderBy(x=>x.TENLOAI);
            if (sANPHAM == null)
            {
                return HttpNotFound();
            }
            ViewBag.SP = sANPHAM.ToList();
            ViewBag.LK = lINHKIEN.ToList();
            return View();
        }

        // GET: Admin/Sanpham/Create
        public ActionResult Create()
        {
            ViewBag.MAHSX = new SelectList(db.hangsanxuat, "MAHSX", "TENHSX");
            ViewBag.MANPP = new SelectList(db.nhaphanphoi, "MANPP", "TENNPP");
            return View();
        }

        // POST: Admin/Sanpham/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SERIAL,MAHSX,MANPP,TENMAY,MODEL,GIA,SOLUONG,THOIHANBAOHANH,IMAGE,MOREIMAGE,GIAKHUYENMAI,DETAIL")] SANPHAM sANPHAM)
        {
            if (ModelState.IsValid)
            {
                db.sanpham.Add(sANPHAM);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MAHSX = new SelectList(db.hangsanxuat, "MAHSX", "TENHSX", sANPHAM.MAHSX);
            ViewBag.MANPP = new SelectList(db.nhaphanphoi, "MANPP", "TENNPP", sANPHAM.MANPP);
            return View(sANPHAM);
        }

        // GET: Admin/Sanpham/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SANPHAM sANPHAM = db.sanpham.Find(id);
            if (sANPHAM == null)
            {
                return HttpNotFound();
            }
            ViewBag.MAHSX = new SelectList(db.hangsanxuat, "MAHSX", "TENHSX", sANPHAM.MAHSX);
            ViewBag.MANPP = new SelectList(db.nhaphanphoi, "MANPP", "TENNPP", sANPHAM.MANPP);
            return View(sANPHAM);
        }

        // POST: Admin/Sanpham/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SERIAL,MAHSX,MANPP,TENMAY,MODEL,GIA,SOLUONG,THOIHANBAOHANH,IMAGE,MOREIMAGE,GIAKHUYENMAI,DETAIL")] SANPHAM sANPHAM)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sANPHAM).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MAHSX = new SelectList(db.hangsanxuat, "MAHSX", "TENHSX", sANPHAM.MAHSX);
            ViewBag.MANPP = new SelectList(db.nhaphanphoi, "MANPP", "TENNPP", sANPHAM.MANPP);
            return View(sANPHAM);
        }


        // POST: Admin/Sanpham/Delete/5
        public ActionResult Delete(string id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SANPHAM sANPHAM = db.sanpham.Find(id);
            if (sANPHAM != null)
            {
                db.sanpham.Remove(sANPHAM);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

    }
}

QLPC/QLPC/Areas/Admin/Views/Sanpham/Create.cshtml
@model QLPC.Models.DataModel.SANPHAM

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    <div class="box box-primary">
        <div class="box-header with-border"><h2>Thêm mới sản phẩm</h2></div>
        <br />
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.SERIAL, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.SERIAL, new { htmlAttributes = new { @class = "form-control", placeholder = "Xem mã trên sản phẩm" } })
                    @Html.ValidationMessageFor(model => model.SERIAL, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MAHSX, "Hãng sản xuất", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.DropDownList("MAHSX", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MAHSX, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MANPP, "Nhà phân phối", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.DropDownList("MANPP", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MANPP, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TENMAY, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.TENMAY, new { htmlAttributes = new { @class = "form-control", placeholder = "Xem tên trên sản phẩm" } })
                    @Html.ValidationMessageFor(model => model.TENMAY, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MODEL, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.MODEL, new { htmlAttributes = new { @class = "form-control", placeholder = "Xem model trên sản phẩm" } })
                    @Html.ValidationMessageFor(model => model.MODEL, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GIA, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.GIA, new { htmlAttributes = new { @class = "form-control", placeholder = "Đơn vị: Việt Nam đồng" } })
                    @Html.ValidationMessageFor(model => model.GIA, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GIAKHUYENMAI, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.GIAKHUYENMAI, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GIAKHUYENMAI, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SOLUONG, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.SOLUONG, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SOLUONG, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.THOIHANBAOHANH, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.THOIHANBAOHANH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.THOIHANBAOHANH, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IMAGE, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.IMAGE, new { htmlAttributes = new { @class = "form-control", type="file" } })
                    @Html.ValidationMessageFor(model => model.IMAGE, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MOREIMAGE, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.MOREIMAGE, new { htmlAttributes = new { @class = "form-control", type="file" } })
                    @Html.ValidationMessageFor(model => model.MOREIMAGE, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DETAIL, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.DETAIL, new { htmlAttributes = new { @class = "form-control", placeholder = "Đánh giá chi tiết sản phẩm" } })
                    @Html.ValidationMessageFor(model => model.DETAIL, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
       
        <div class="form-group box-footer">
            <div class="col-md-offset-3 col-md-9">
                <span>
                    <input type="submit" value="Thêm" class="btn btn-primary btn" /> &nbsp &nbsp
                    <a href="/Admin/Sanpham/Index"><input class="btn btn-default" type="button" value="Hủy" /></a>
                </span>
            </div>
        </div>
    </div>
}

QLPC/QLPC/Areas/Admin/Views/Sanpham/Details.cshtml
@model QLPC.Models.DataModel.SANPHAM

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    string ID = "1";
}


<div class="box box-primary">
    <div class="box-header "><h2>Chi tiết sản phẩm</h2></div>
    <br />
    <div>
        <table class="table">

@foreach (var item in ViewBag.SP)
{
    ID = item.SERIAL;
                <tr>
                    <td class="col-md-3" rowspan="9" width="250"><img src="@item.IMAGE" width="250" height="250" /><br /><br/>
                    <div>
                        <button type="button" class="btn btn-default " data-toggle="modal" data-target="#myModal1">Xem thêm ảnh</button>
                        <button type="button" class="btn btn-default pull-right" data-toggle="modal" data-target="#myModal2">Cấu hình máy</button>
                        <!-- Modal của nút Xem thêm ảnh-->
                        <div class="modal fade" id="myModal1" role="dialog">
                            <div class="modal-dialog">
                                <!-- Nội dung modal-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h2 class="modal-title">Danh sách ảnh</h2>
                                    </div>
                                    <div class="modal-body">
                                        <p>Hiện tại chưa có nhiều ảnh cho sản phẩm</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Modal của nút Xem cấu hình-->
                        <div class="modal fade" id="myModal2" role="dialog">
                            <div class="modal-dialog">
                                <!-- Nội dung modal-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h3 class="modal-title">Cấu hình sản phẩm: @item.TENMAY @item.MODEL</h3>
                                    </div>
                                    <div class="modal-body text-center">
                                        @foreach (var item2 in ViewBag.LK) {
                                            <dl class="dl-horizontal">
                                            @if (item2.TENLOAI == "LCD")
                                               {<dt>Màn hình (LCD):</dt>                                           
                                                <dd> @item2.TENLK;</dd>}
                                        
                                            @if (item2.TENLOAI == "CPU")
                                                {<dt>Bộ xử lý (CPU):</dt>                                            
                                                <dd>@item2.TENLK;</dd>}
                                            @if (item2.TENLOAI == "RAM")
                                                {<dt>Bộ nhớ Ram:</dt>                                           
                                                <dd>@item2.TENLK</dd>}

                                           @if (item2.TENLOAI == "HDD")
                                                {<dt>Ổ cứng HDD:</dt>                                            
                                                <dd>@item2.TENLK</dd>}

                                           @if (item2.TENLOAI == "OS")
                                                {<dt>Hệ điều hành (OS):</dt>
                                                <dd>@item2.TENLK</dd>}

                                           @if (item2.TENLOAI == "ODD")
                                                {<dt>Đĩa quang (ODD): </dt>                                         
                                                <dd>@item2.TENLK</dd>}
                                            
                                           @if (item2.TENLOAI == "Lan/Wireless")
                                                {<dt>Card mạng (Lan/Wireless):</dt>                                           
                                                <dd>@item2.TENLK</dd>}
                                            
                                           @if (item2.TENLOAI == "BlueTooth")
                                                {<dt>BlueTooth:</dt>
                                                <dd>@item2.TENLK</dd>}
                                            
                                           @if (item2.TENLOAI == "Cardreader")
                                                {<dt>Cardreader:</dt>                                                                                       
                                                <dd>@item2.TENLK</dd>}                                            

                                           @if (item2.TENLOAI == "Camera")
                                                {<dt>Camera:</dt>                                            
                                                <dd>@item2.TENLK</dd>}
                                            
                                            @if (item2.TENLOAI == "Fingerprint")
                                                {<dt>Fingerprint:</dt>                                          
                                                <dd>@item2.TENLK</dd>}
                                            
                                            @if (item2.TENLOAI == "Pin/ Adapter")
                                                {<dt>Pin/ Adapter:</dt>                                          
                                                <dd>@item2.TENLK</dd>}                                           
                                        </dl>
                                                    }
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    </td>
                    <th class="col-md-1">Tên máy:</th>
                    <td class="col-md-2"><p style="color:blue">@item.TENMAY</p></td>
                    <th class="col-md-1">Nhà phân phối:</th>
                    <td class="col-md-1">@item.NHAPHANPHOI.TENNPP</td>
                    <th class="col-md-1">Số lượng:</th>
                    <td class="col-md-1">@item.SOLUONG</td>
                    <th class="col-md-1">Giá niêm yết (đ):</th>
                    <td class="col-md-1">@item.GIA</td>
                </tr>
                <tr>
                    <th>Mã hiệu:</th>
                    <td class="col-md-2"><p style="color:blue">@item.MODEL</p></td>
                    <th>Hãng sản xuất:</th>
                    <td>@item.HANGSX.TENHSX</td>
                    <th>Bảo hành (tháng):</th>
                    <td>@item.THOIHANBAOHANH</td>
                    <th>Giá khuyến mãi:</th>
                    <td>@item.GIAKHUYENMAI</td>
                </tr>

                <tr>
                    <th >Mô tả chi tiết:</th>
                    <td colspan="7">@item.DETAIL</td>
                </tr>
}
        </table>

    </div>
    <div class="form-group box-footer">
        <div class="col-md-offset-3 col-md-9">
            <span>
                <button type="button" onclick="location.href=' @Url.Action("Edit", "Sanpham", new { id = ID })'" class="btn btn-primary">Cập nhật</button>
                <a href="/Admin/Sanpham/Index"><input class="btn btn-default" type="button" value="Trở về" /></a>
            </span>
        </div>
    </div>
</div>

QLPC/QLPC/Areas/Admin/Views/Sanpham/Index.cshtml
@model IEnumerable<QLPC.Models.DataModel.SANPHAM>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@using PagedList.Mvc;
@using PagedList;


<div class="box box-primary">
    <div class="box-header with-border">
        <h2>Danh sách sản phẩm</h2>
    </div>

    <a href="/Admin/Sanpham/Create"><input class="btn btn-primary" type="button" value="Thêm mới sản phẩm" /></a>
    <table class="table table-responsive table-hover table-bordered table-condensed " >
        <tr class="info">
            <th class="2" >
                @Html.DisplayNameFor(model => model.SERIAL)
            </th>
            <th class="col-md-2">
                @Html.DisplayNameFor(model => model.TENMAY)
            </th>
            <th class="col-md-2">
                @Html.DisplayNameFor(model => model.MODEL)
            </th>
            <th class="col-md-2">
                @Html.DisplayNameFor(model => model.GIA)
            </th>
            <th class="col-md-1">
                @Html.DisplayNameFor(model => model.SOLUONG)
            </th>
            <th class="col-md-1">
                @Html.DisplayNameFor(model => model.IMAGE)
            </th>
            <th class="col-md-2">Tùy chọn</th>
        </tr>

        @foreach (var item in ViewBag.sanpham)
        {
            <tr class="active  ">
                <td>
                    @item.SERIAL
                </td>
                <td>
                    @item.TENMAY
                </td>
                <td>
                    @item.MODEL
                </td>
                <td>
                    @item.GIA
                </td>
                <td>
                    @item.SOLUONG
                </td>
                <td>
                    <img src="@item.IMAGE" width="100" height="100"/>
                </td>
                <td>
                    <div class="btn-group ">
                        @Html.ActionLink(" ", "Edit", new { id = item.SERIAL }, new { @class = "btn btn-primary glyphicon glyphicon-edit", data_toggle = "tooltip", title = "Cập nhật" })
                        @Html.ActionLink(" ", "Details", new { id = item.SERIAL }, new { @class = "btn btn-primary glyphicon glyphicon-list-alt", data_toggle = "tooltip", title = "Xem" })
                        @Html.ActionLink(" ", "Delete", new { id = item.SERIAL }, new { @class = "btn btn-primary glyphicon glyphicon-remove-sign disabled", data_toggle = "tooltip", title = "Xóa", @onclick = "return confirm('Sản phẩm này sẽ được xóa khỏi danh dách! Bạn có muốn xóa?');" })
                    </div>
                </td>
            </tr>
        }
    </table>

    <div>
        @Html.PagedListPager((IPagedList)ViewBag.sanpham, page => Url.Action("Index", new { page }))
    </div>
</div>

<script>
$(document).ready(function(){
    $('[data_toggle="tooltip"]').tooltip();
});
</script>